### ISSUE TITLE
not working on magento 2.4.6

### ISSUE THREAD

**Issue by harishkhant** [owebia/magento2-module-shared-php-config#9] opened 2023-05-23 09:35 UTC
https://dev.comartex.com/checkout/cart/#:~:text=Error%3A%20Cannot%20instantiate%20interface%20Owebia%5CSharedPhpConfig%5CApi%5CParserInterface%20in%20/home/dev_comartex/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php%3A121%0AStack%20trace%3A

![image](https://github.com/owebia/magento2-module-shared-php-config/assets/64633051/04fcd0f2-20ed-404a-a608-55751ee3191a)

owebia/magento2-module-shared-php-config after installing this module we faced an error on the checkout page.

**Comment by owebia** [comment] 2023-05-24 06:57
Closing duplicate of https://github.com/owebia/magento2-module-advanced-shipping/issues/115

**Closed as completed by owebia** 2023-05-24 06:57 UTC
Labels: duplicate
